
include(${DEV_ROOT_PATH}/MenuSystem/AutoGen.cmake)
include(${DEV_ROOT_PATH}/CameraController/AutoGen.cmake)
include(${DEV_ROOT_PATH}/UpdatableObjects/AutoGen.cmake)
include(${DEV_ROOT_PATH}/Common/Math/AutoGen.cmake)
include(${DEV_ROOT_PATH}/Common/Util/AutoGen.cmake)
include(${DEV_ROOT_PATH}/Common/XMLHelper/AutoGen.cmake)
include(${DEV_ROOT_PATH}/IA/AutoGen.cmake)
include(${DEV_ROOT_PATH}/BillboardManager/AutoGen.cmake)
include(${DEV_ROOT_PATH}/Common/DotSceneLoader/AutoGen.cmake)
include(${DEV_ROOT_PATH}/PathfindingSystem/AutoGen.cmake)
include(${DEV_ROOT_PATH}/CollisionSystem/AutoGen.cmake)
include(${DEV_ROOT_PATH}/MainStateMachine/AutoGen.cmake)
include(${DEV_ROOT_PATH}/LoadingSystem/AutoGen.cmake)
include(${DEV_ROOT_PATH}/LevelManager/AutoGen.cmake)
include(${DEV_ROOT_PATH}/Common/GUIHelper/AutoGen.cmake)
include(${DEV_ROOT_PATH}/Utils/GUI/AutoGen.cmake)
include(${DEV_ROOT_PATH}/GameUnits/AutoGen.cmake)
